import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { KbLayout } from "../components/kb-layout";
import { SettingsProvider } from "../components/settings-provider";
import { ReactQueryProvider } from "../components/react-query-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <SettingsProvider>
            <KbLayout>{children}</KbLayout>
          </SettingsProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
